apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctr
  template:
    metadata:
      labels:
        app: doctr
    spec:
      containers:
        - name: doctr
          image: REPLACE_IMAGE
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
